# domain means self domain, it will use this to reverse connect to remote peer
# domain not means hostname, one domain maybe consist of a lot of hosts
# so, if here config a item : domain1 127.0.0.1:8001
# domain1 may include host1, host2, when host1 got the addrs, it will parse the addr list,
# and got the domain1's addr to reverse connect. The same to host2.
# Chinese:
# 一个domain可能拥有多个host,一个主机只需要归属一个domain即可，在连接的时候会用自己的domain来匹配下面的
# ip地址列表，举例来说：
# host1 属于domain1
# host2 属于domain1
# host3 属于domain2
# host1需要配置两个domain下的归属地址：

# host1 domain1:
# domain1: 172.16.0.1:1234
# domain2: 192.168.10.1:1234

# host2 domain1:
# domain1: 172.16.0.2:1234
# domain2: 192.168.10.2:1234

#host3 domain2:
# domain1: 172.16.0.2:1234
# domain2: 192.168.10.2:1234

# host3 在连接host1,host2 的时候，就会用domain1的地址连接

domain = "domain1"

# addr is (domain,endpoint) pair, those items defined the ip address:port which
# other domains' host how connect to self
addrs = [
 "domain1 127.0.0.1:50011",
 "domain2 127.0.0.1:50011",
 "domain3 127.0.0.1:50011",
 "domain4 127.0.0.1:50011",
]
